### ISSUE TITLE
 Failed to login. | Error: Used disallowed intents | src/bot.js

### ISSUE THREAD

**Issue by justmohamedd** [HimejiDev/Ryuk#1]
getting this error after entering token (after the whole Y/N stuff)
idrk about coding but maybe a simple fix for this or if its something wrong im doing

**Comment by HimejiDev** [comment]
Hi, you probably forgot to turn all the "Privileged Gateway Intents" on. You can do that in de [Developer Portal](https://discord.com/developers/) under "Bot" (on the left side).
![image](https://github.com/HimejiDev/Ryuk/assets/88136704/7ed7e2a4-3ef8-443a-8361-03769b06d392)
Let me know if this fixed the issue! :)
